# Generated by Django 5.0.7 on 2024-08-21 17:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_contacts_email_alter_contacts_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='name',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='contacts',
            name='appeal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contacts',
            name='cassation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contacts',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contacts',
            name='data',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='contacts',
            name='defendant',
            field=models.CharField(default='Unknown Defendant', max_length=255),
        ),
        migrations.AddField(
            model_name='contacts',
            name='executionOrder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contacts',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contacts',
            name='plaintiff',
            field=models.CharField(default='Unknown Plaintiff', max_length=255),
        ),
        migrations.AddField(
            model_name='contacts',
            name='preparation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contacts',
            name='status',
            field=models.CharField(choices=[('under_review', 'Under Review'), ('appeal', 'Appeal'), ('cassation', 'Cassation'), ('preparation', 'Preparation'), ('completed', 'Completed')], default='Under Review', max_length=20),
        ),
        migrations.AddField(
            model_name='contacts',
            name='under_review',
            field=models.BooleanField(default=False),
        ),
    ]
